swagger: '2.0'
info:
  $ref: ./info.yaml
host: app.launchdarkly.com
basePath: /api/v2
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Token:
    type: apiKey
    name: Authorization
    in: header
    description: https://app.launchdarkly.com/settings#/tokens
security:
  - Token: []
paths:
  $ref: ./paths.yaml
definitions:
  $ref: ./definitions.yaml
responses:
  $ref: ./responses.yaml
parameters:
  $ref: ./parameters.yaml