WebhookId:
  name: webhookId
  in: path
  required: true
  description: The webhook ID
  type: string
WebhookPostRequest:
  name: webhookPost
  in: body
  required: true
  description: New webhook
  schema:
    properties:
      url:
        type: string
      secret:
        type: string
      sign: 
        type: boolean
      on: 
        type: boolean
    required:
      - url
      - sign
      - on
PatchRequest:
  name: patchDelta
  in: body
  required: true
  description: http://jsonpatch.com/
  schema:
    properties:
      op:
        type: string
      path:
        type: string
      value:
        type: object
    required:
      - op
      - path
      - value