version: 2

# Keep this at the top to reduce noise in chatrooms when we mess up circleci setup
experimental:
  notify:
    branches:
      only:
      - master

jobs:
  build:
    docker:
    - image: circleci/node:10-browsers  # -browsers image has java but is otherwise relatively small
    steps:
    - checkout
    - run:
        name: Install Swagger Codegen
        command: |
          wget http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/2.3.1/swagger-codegen-cli-2.3.1.jar -O swagger-codegen-cli.jar
          printf '#!/bin/bash\nexec java -jar /usr/local/bin/swagger-codegen-cli.jar "$@"\n' > ./swagger-codegen
          sudo mv ./swagger-codegen /usr/local/bin
          sudo mv ./swagger-codegen-cli.jar /usr/local/bin
          sudo chmod +x /usr/local/bin/swagger-codegen

    - run:
        name: Loading previous client repos
        command: |
          export REPO_USER_URL=https://github.com/$CIRCLE_PROJECT_USERNAME
          make load_prior_targets

    - run:
        name: Generating code
        command: |
          export REPO_USER_URL=https://github.com/$CIRCLE_PROJECT_USERNAME
          make all

    - run:
        name: Archiving targets
        command: |
          cd targets
          VERSION=$(cat openapi.json | jq -r '.info.version')
          tar cvfz api-clients-${VERSION}-${CIRCLE_SHA1:0:7}.tgz api-client-*
          mkdir /tmp/api-clients
          cp api-clients-*.tgz /tmp/api-clients

    - persist_to_workspace:
        root: targets
        paths:
        - .

    - store_artifacts:
        path: targets/html2
        destination: html

    - store_artifacts:
        path: targets/html
        destination: html-plain

    - store_artifacts:
        path: /tmp/api-clients

  publish:
    docker:
    - image: circleci/openjdk:10-browsers
      environment:
        GRADLE_USER_HOME: /home/circleci
    steps:
    - checkout
    - attach_workspace:
        at: targets

    - run:
        name: Install AWS CLI
        command: |
          curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
          unzip awscli-bundle.zip
          sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

    - run:
        name: Install GHR (Github Releaser)
        command: |
          curl -L https://github.com/tcnksm/ghr/releases/download/v0.10.2/ghr_v0.10.2_linux_amd64.tar.gz | tar xz
          sudo mv ghr_v0.10.2_linux_amd64/ghr /usr/local/bin
          sudo chmod a+x /usr/local/bin/ghr

    - run:
        name: Publishing GitHub Release
        command: |
          cd targets
          for file in openapi.{json,yaml} api-clients-*.tgz; do
            ghr -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME $CIRCLE_TAG $file
          done

    - run:
        name: Pushing updated client repos
        command: |
          git config --global user.name $GH_USER
          git config --global user.email $GH_EMAIL
          make TAG=$CIRCLE_TAG push

    - run:
        name: Fetching credentials
        command: |
          aws s3 cp s3://launchdarkly-pastebin/ci/openapi/gradle.properties.enc .
          aws s3 cp s3://launchdarkly-pastebin/ci/openapi/secring.gpg.enc .
          openssl enc -d -in gradle.properties.enc -aes-256-cbc -k $ENCRYPTION_SECRET -md md5 > ~/gradle.properties
          openssl enc -d -in secring.gpg.enc -aes-256-cbc -k $ENCRYPTION_SECRET -md md5 > ~/secring.gpg

    - run:
        name: Publish packages
        command: |
          if [ "$CIRCLE_REPO" = "https://github.com/launchdarkly/ld-openapi" ]; then
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            make PUBLISH_TARGETS="java javascript" publish
          fi

  test-go:
    docker:
    - image: circleci/golang
    steps:
    - checkout
    - attach_workspace:
        at: targets
    - run:  |
        mkdir -p /go/src/github.com/launchdarkly
        cp -r targets/api-client-go /go/src/github.com/launchdarkly/
    - run: |
        cd samples/go
        make

  test-javascript:
    docker:
    - image: circleci/node
    steps:
    - checkout
    - attach_workspace:
        at: targets
    - run: |
        cd samples/javascript
        sudo npm link ../../targets/api-client-javascript
        node index.js

workflows:
  version: 2
  build:
    jobs:
    - build:
        filters:
          branches:
            ignore:
            - gh-pages
          tags:
            only:
              /.*/ # Required in order to run publish job for a tag push
    - test-go:
        requires:
        - build
    - test-javascript:
        requires:
        - build
    - publish:
        requires:
        - build
        filters:
          tags:
            only: /^\d+\.\d+\.\d+.*$/
          branches:
            ignore: /.*/
        context: org-global  # includes the s3 access key needed to get credentials
